apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-data
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: {{ .Values.authService.persistence.storageClass }}

  resources:
    requests:
      storage: {{ .Values.authService.persistence.size }}