apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cloud-commerce-aws-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: cloud-commerce
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloud-commerce-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: cloud-commerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloud-commerce-aws-secrets
    kind: SecretStore
  target:
    name: cloud-commerce-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: cloud-commerce/prod
        property: JWT_SECRET

    - secretKey: RAZORPAY_KEY_ID
      remoteRef:
        key: cloud-commerce/prod
        property: RAZORPAY_KEY_ID

    - secretKey: RAZORPAY_KEY_SECRET
      remoteRef:
        key: cloud-commerce/prod
        property: RAZORPAY_KEY_SECRET

    - secretKey: RAZORPAY_WEBHOOK_SECRET
      remoteRef:
        key: cloud-commerce/prod
        property: RAZORPAY_WEBHOOK_SECRET
