grafana:
  enabled: true
  adminUser: admin
  adminPassword: "CHANGE-ME-BEFORE-PRODUCTION"
  service:
    type: ClusterIP
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

prometheus:
  enabled: true
  prometheusSpec:
    retention: 24h
    retentionSize: 2GB
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    storageSpec: {}

alertmanager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false
